version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: 'orderbot'
      MYSQL_USER: 'mfuatnuroglu'
      MYSQL_PASSWORD: 'Fouad@Fouad1'
      MYSQL_ROOT_PASSWORD: 'Fouad@Fouad1'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
