export enum PermessionEnum {
    SHOW_ROLE = "SHOW_ROLE",
    SHOW_USER = "SHOW_USER",
    ADD_USER = "ADD_USER",
    DELETE_USER = "DELETE_USER",
    UPDATE_USER = "UPDATE_USER",
    ADD_ROLE = "ADD_ROLE",
    DELETE_ROLE = "DELETE_ROLE",
    UPDATE_ROLE = "UPDATE_ROLE",
    UPATE_PERMESSIONS = "UPATE_PERMESSIONS",

}