export enum CallBackQueryResult {
    StartOrdering = "START_ORDERING",
    AddToBasket = "ADD_TO_BASKET",
    //AddToBasketAndCompleteOrder = "ADD_TO_BASKET_COMPLETE_ORDER",
    TrackOrder = "ORDER_TRACKING",
    MyBasket = "MY_ORDERS",
    //AddressRequest = "ADRESS_REQUEST",
    //SearchAgain = "SEARCH_AGAIN",
    //IncreaseOrder = "IncreaseOrder",
    //GoToPayment = "GO_TO_PAYMENT",
    CompleteOrder = "COMPLETE_ORDER",
    AddProductAndCompleteOrder = "ADD_PRODUCT_AND_COMPLETE_ORDER",
    EnterAddress = "ENTER_ADDRESS",
    SendOrder = "SEND_ORDER",
    ConfirmOrder = "CONFIRM_ORDER",
    EmptyBakset = "EMPTY_BASKET",
    MainMenu = "MAIN_MENU",
    AddNoteToOrder = "ADD_NOTE_TO_ORDER",
    GetConfirmedOrders = "GET_CONFIRMED_ORDERS",
}