export enum CallBackQueryResult {
  StartOrdering = 'START_ORDERING',
  AddToBasketAndContinueShopping = 'ADD_TO_BASKET',
  TrackOrder = 'ORDER_TRACKING',
  MyBasket = 'MY_ORDERS',
  CompleteOrder = 'COMPLETE_ORDER',
  AddProductAndCompleteOrder = 'ADD_PRODUCT_AND_COMPLETE_ORDER',
  EnterAddress = 'ENTER_ADDRESS',
  SendOrder = 'SEND_ORDER',
  ConfirmOrder = 'CONFIRM_ORDER',
  EmptyBakset = 'EMPTY_BASKET',
  MainMenu = 'MAIN_MENU',
  AddNoteToOrder = 'ADD_NOTE_TO_ORDER',
  GetConfirmedOrders = 'GET_CONFIRMED_ORDERS',
}
